// Secrets set with `wrangler secret put`. Everything else in Env is generated by `wrangler types`.
interface Env {
  JWT_PRIVATE_KEY: string;
  JWT_PUBLIC_KEYS: string;
  IP_HASH_SALT: string;
  GITHUB_CLIENT_SECRET: string;
}
